stages:
  - build

default:
  image: docker:24.0.7-git
  services:
    - docker:24.0.7-dind
  before_script:
    - docker info

build_image:
  stage: build
  script:
    - IMAGE_NAME=$(echo $CI_COMMIT_TAG | cut -d / -f 1)
    - IMAGE_VERSION=$(echo $CI_COMMIT_TAG | cut -d / -f 2)
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --compress --squash --rm -t $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_VERSION -f $IMAGE_NAME/Dockerfile --build-arg BUILD_TAG=$IMAGE_VERSION --no-cache $IMAGE_NAME
    - docker push $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_VERSION
    - docker logout
  tags:
    # This tag labels all the runners with privileged permissions, per the GitLab documentation:
    # https://gitlab.docs.cern.ch/docs/Build%20your%20application/CI-CD/Runners/docker-privileged-runners/
    - docker-privileged-xl
  only:
    - tags